[package]
name = "letter-boxed-solver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
env_logger = "0.8.4"
lazy_static = "1.4.0"
log = "0.4.14"
onig = "6.2.0"
